apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-backend
  template:
    metadata:
      labels:
        app: nestjs-backend
    spec:
      containers:
      - name: nestjs-container
        image: gusrsl/kuber-az:latest
        imagePullPolicy: Always  # Always obtener la última imagen
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: DATABASE_URL
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: DATABASE_PASSWORD
