apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring  # Asegúrate de que el servicio esté en el mismo espacio de nombres que Prometheus
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
